name: Trigger auto deployment for capp2newpython

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp2newpython-AutoDeployTrigger-1964a58a-12aa-4c7c-8f36-af7e3710bff1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPP2NEWPYTHON_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPP2NEWPYTHON_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPP2NEWPYTHON_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPP2NEWPYTHON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPP2NEWPYTHON_REGISTRY_PASSWORD }}
          containerAppName: capp2newpython
          resourceGroup: test2-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


