name: Trigger auto deployment for sample-containerapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-containerapp2-AutoDeployTrigger-e0dbf0d0-5d37-433c-a674-de708ed9b3e0.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLECONTAINERAPP2_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca52ad379c7cacr.azurecr.io
          registryUsername: ${{ secrets.SAMPLECONTAINERAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLECONTAINERAPP2_REGISTRY_PASSWORD }}
          containerAppName: sample-containerapp2
          resourceGroup: ca-snehapar-group
          imageToBuild: ca52ad379c7cacr.azurecr.io/sample-containerapp2:${{ github.sha }}
          
            

     

