name: Trigger auto deployment for sample-containerapp3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-containerapp3-AutoDeployTrigger-a7b24c1e-c627-4abd-b88a-dda154f31601.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLECONTAINERAPP3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca52ad379c7cacr.azurecr.io
          registryUsername: ${{ secrets.SAMPLECONTAINERAPP3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLECONTAINERAPP3_REGISTRY_PASSWORD }}
          containerAppName: sample-containerapp3
          resourceGroup: ca-snehapar-group
          imageToBuild: ca52ad379c7cacr.azurecr.io/sample-containerapp3:${{ github.sha }}
          
            

     

