name: Trigger auto deployment for sample-containerapp4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sample-containerapp4-AutoDeployTrigger-9060b3e0-23e6-4f39-ba37-4ebc2f71125e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLECONTAINERAPP4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca52ad379c7cacr.azurecr.io
          registryUsername: ${{ secrets.SAMPLECONTAINERAPP4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SAMPLECONTAINERAPP4_REGISTRY_PASSWORD }}
          containerAppName: sample-containerapp4
          resourceGroup: ca-snehapar-group
          imageToBuild: ca52ad379c7cacr.azurecr.io/sample-containerapp4:${{ github.sha }}
          
            

     

